apiVersion: v1
kind: ConfigMap
metadata:
  name: personal-config-${STUDENT_ID}
data:
  index.html: |
    <h1>Привет от ${YOUR_NAME}!</h1>
    <p>Группа: ${YOUR_GROUP}</p>
    <p>Номер студенческого билета: ${YOUR_VARIANT}</p>  # 2xxxxxx
  # ЗАМЕНИТЕ НА СВОИ ДАННЫЕ!
